### ISSUE TITLE
ADDITIONAL MGMT NETWORKS - should be optional but is mandatory

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#366] opened 2017-01-12 08:17 UTC
ADDITIONAL MGMT NETWORKS should be optional attribute

**Comment by TaiTheGreat** [comment] 2017-01-12 13:09
@apiddubny  This is still reproducing for Tor and me with a new build and a new package. Any ideas?

**Comment by apiddubny** [comment] 2017-01-12 15:40
@TaiTheGreat 
do you have some logs for failed deployment?

**Comment by TaiTheGreat** [comment] 2017-01-15 12:56
turns out it was just not checked in to the develop yet. verified now.

**Closed** 2017-01-15 12:56 UTC
Labels: bug, in test, P3, Version 7.2
