### ISSUE TITLE
Refresh IP On Public IP

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#186] opened 2016-11-22 16:00 UTC
@apiddubny  Refresh IP command not obtained the public IP.
Only the Private IP is updated.

**Comment by apiddubny** [comment] 2016-11-25 14:29
@yairbb 
Can't reproduce the issue, can you please add some more steps? 
Also are you sure that Deployed App have "Add Public IP" attribute set to True?

**Comment by yairbb** [comment] 2016-11-27 05:47
1) Have a reservation with deployed App.
2) assign to that public IP via Azure.
3) perform Refresh ip command. 
4) Verify in cloud shell that the public Ip was updated in right side pane.

**Comment by TomerAdmon** [comment] 2016-11-28 15:00
Hi, 
when a public IP was assigned to a vm, this is the ip that should be set as the resource address since we need it for other operations such as QualiX, installation script ect...
@apiddubny , @yairbb

**Comment by yairbb** [comment] 2016-11-28 15:43
@TomerAdmon @apiddubny 

Tomer it will be problematic since in the sendbox we will have mix of IP some are public ( due to the allocation) and some are Private. is that good from your side ? There is an option that in case we allocate public IP it will be presented in the right side panel.

**Closed** 2016-12-04 07:48 UTC
Labels: bug, P1, Version 7.1
