### ISSUE TITLE
Azure VM Outbound attribute should be remove

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#193] opened 2016-11-24 06:14 UTC
Azure VM Outbound attribute should be remove from the service
![image](https://cloud.githubusercontent.com/assets/17527106/20588465/fba6e7b8-b21d-11e6-9e71-267aad9a07a3.png)

**Comment by alexazarh** [comment] 2016-12-07 08:36
duplicate of #59

**Closed** 2016-12-07 08:35 UTC
Labels: bug, Canceled, P3, Version 7.2
