### ISSUE TITLE
Testing only - Verify connectivity in Azure

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#35] opened 2016-09-21 13:01 UTC

**Comment by yairbb** [comment] 2016-11-17 13:28
Reminder to check the connectivity between the machines after deployment from Azure side.

**Comment by yairbb** [comment] 2016-11-28 10:29
Duplicate of #179

**Comment by tornizanQ** [comment] 2016-12-14 14:49
[test plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=158027)

**Comment by tornizanQ** [comment] 2016-12-19 05:15
blocked by bug 
https://github.com/QualiSystems/Azure-Shell/issues/276

**Closed** 2016-12-22 12:46 UTC
Labels: Test Plan Ready, Testing Only, Version 7.2
