### ISSUE TITLE
Description Error: Region

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#267] opened 2016-12-14 15:18 UTC
Mismatch:

RM:" The Azure region to be used by this cloud provider resource."
Conf:"The public cloud region to be used by this cloud provider resource."

The desciption shall be more generic like conf.

**Comment by alexazarh** [comment] 2016-12-14 15:51
duplicate of #262

**Closed** 2016-12-14 15:52 UTC
Labels: bug, Canceled, New, P2
